# Generated by Django 5.0.1 on 2025-12-07 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.BigIntegerField(db_index=True, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("member_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Telegram Group",
                "verbose_name_plural": "Telegram Groups",
                "db_table": "telegram_groups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.BigIntegerField(db_index=True, unique=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("is_bot", models.BooleanField(default=False)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Telegram User",
                "verbose_name_plural": "Telegram Users",
                "db_table": "telegram_users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.BigIntegerField(db_index=True)),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("photo", "Photo"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("voice", "Voice"),
                            ("document", "Document"),
                            ("sticker", "Sticker"),
                            ("animation", "Animation"),
                            ("location", "Location"),
                            ("contact", "Contact"),
                            ("poll", "Poll"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "media_file_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "media_file_unique_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("media_file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "media_mime_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reply_to_message_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("forward_from_user_id", models.BigIntegerField(blank=True, null=True)),
                ("forward_from_chat_id", models.BigIntegerField(blank=True, null=True)),
                ("raw_json", models.JSONField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("is_edited", models.BooleanField(db_index=True, default=False)),
                ("telegram_created_at", models.DateTimeField()),
                ("telegram_edited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        db_column="reply_to_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="core.message",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.telegramgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "messages",
                "ordering": ["-telegram_created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                            ("question", "Question"),
                        ],
                        db_index=True,
                        max_length=20,
                        null=True,
                    ),
                ),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("intent", models.CharField(blank=True, max_length=100, null=True)),
                ("keywords", models.JSONField(blank=True, null=True)),
                ("regex_matches", models.JSONField(blank=True, null=True)),
                ("is_question", models.BooleanField(db_index=True, default=False)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="core.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Analysis",
                "verbose_name_plural": "Message Analyses",
                "db_table": "message_analysis",
                "ordering": ["-analyzed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["group", "-telegram_created_at"],
                name="messages_group_i_9b1bac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["user", "-telegram_created_at"],
                name="messages_user_id_22fa89_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["media_type", "-telegram_created_at"],
                name="messages_media_t_53d6cc_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="message",
            unique_together={("message_id", "group")},
        ),
    ]
