# Generated by Django 6.0 on 2025-12-07 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_text", models.TextField(blank=True, null=True)),
                ("new_text", models.TextField(blank=True, null=True)),
                ("edited_at", models.DateTimeField(auto_now_add=True)),
                ("edit_metadata", models.JSONField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_history",
                        to="core.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message History",
                "verbose_name_plural": "Message Histories",
                "db_table": "message_history",
                "ordering": ["-edited_at"],
            },
        ),
    ]
