# Generated by Django 6.0 on 2025-12-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_messagehistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("photo", "Photo"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("voice", "Voice"),
                    ("document", "Document"),
                    ("sticker", "Sticker"),
                    ("animation", "Animation"),
                    ("video_note", "Video Note"),
                    ("location", "Location"),
                    ("contact", "Contact"),
                    ("poll", "Poll"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="text",
                max_length=20,
            ),
        ),
    ]
