# Generated by Django 6.0 on 2025-12-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_message_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="ai_error",
            field=models.TextField(
                blank=True, help_text="AI processing error if any", null=True
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="ai_processed",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Whether AI analysis completed"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="ai_processed_at",
            field=models.DateTimeField(
                blank=True, help_text="When AI analysis was performed", null=True
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sentiment",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="AI-detected sentiment: positive, negative, neutral",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="topics",
            field=models.JSONField(
                blank=True,
                help_text="AI-extracted topics/keywords list: ['yordam', 'savol']",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="messageanalysis",
            name="intent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("question", "Question"),
                    ("complaint", "Complaint"),
                    ("request", "Request"),
                    ("feedback", "Feedback"),
                    ("greeting", "Greeting"),
                    ("other", "Other"),
                ],
                db_index=True,
                help_text="AI-detected user intent",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="messageanalysis",
            name="is_question",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Is this a question? (AI-detected)",
            ),
        ),
        migrations.AlterField(
            model_name="messageanalysis",
            name="keywords",
            field=models.JSONField(
                blank=True,
                help_text="AI-extracted keywords list: ['yordam', 'savol', 'PDF']",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="messageanalysis",
            name="regex_matches",
            field=models.JSONField(
                blank=True, help_text="Legacy regex matches (deprecated)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="messageanalysis",
            name="sentiment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("positive", "Positive"),
                    ("negative", "Negative"),
                    ("neutral", "Neutral"),
                    ("question", "Question"),
                ],
                db_index=True,
                help_text="AI-detected sentiment",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="messageanalysis",
            name="sentiment_score",
            field=models.FloatField(
                blank=True, help_text="Numeric score: -1.0 to 1.0", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sentiment"], name="messages_sentime_d28e10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["ai_processed"], name="messages_ai_proc_80799a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageanalysis",
            index=models.Index(fields=["intent"], name="message_ana_intent_4c5d8a_idx"),
        ),
    ]
