# Generated by Django 6.0 on 2025-12-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_message_ai_error_message_ai_processed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="media_file_name",
            field=models.CharField(
                blank=True,
                help_text="Original file name: photo_123.jpg",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="media_file_path",
            field=models.CharField(
                blank=True,
                help_text="Local file path relative to MEDIA_ROOT: telegram/2024/12/10/photo_123.jpg",
                max_length=500,
                null=True,
            ),
        ),
    ]
